spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shoppingmall
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug